// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAw2Lm9RFyXNWFdwG3T8gRauPA9Fn9N0M',
    appId: '1:966993741392:web:f083c9a513fae89d9ab355',
    messagingSenderId: '966993741392',
    projectId: 'quizzling-app',
    authDomain: 'quizzling-app.firebaseapp.com',
    storageBucket: 'quizzling-app.appspot.com',
    measurementId: 'G-VZY3TVKDSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD66MbWkaUycePmHzAkPVjwu-9nhtaOMB4',
    appId: '1:966993741392:android:6e1295b9788bb5a89ab355',
    messagingSenderId: '966993741392',
    projectId: 'quizzling-app',
    storageBucket: 'quizzling-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDolsI3zqE-vYxNju22P__2-GoeMb3tk2Q',
    appId: '1:966993741392:ios:b5bc409ae12041ee9ab355',
    messagingSenderId: '966993741392',
    projectId: 'quizzling-app',
    storageBucket: 'quizzling-app.appspot.com',
    iosBundleId: 'com.example.quizzling',
  );
}
